name: Start app and run UI tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      
    - name: Start Frontend
      run: |
        npm run start &
        sleep 5 &&
        curl http://localhost:3000 -I
    - name: Start Backend
      run: |
        node /home/runner/work/Library-Catalog-GitHubActions-Exercise/Library-Catalog-GitHubActions-Exercise/server/server.js &
        sleep 5 &&
        curl http://localhost:3030 -I
        
    - name: Install Playwright browsers
      run: npm run playwright-browsers
      
    - name: Run tests with Playwright
      run: npm run ui-test
