name: Start app and run UI tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Start Backend
      run: |
        cd server &&
        npm run start-backend &
        sleep 5 &&
        curl http://localhost:port -I
        
    - name: Start Frontend
      run: |
        npm run start &
        sleep 5 &&
        curl http://localhost:port -I    

    - name: Run tests with Playwright
      run: npm run test
