name: Start app and run UI tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Start frontend
      run: npm run start

    - name: Reach server directory
      run: cd server

    - name: Reach server directory
      run: node server.js

    - name: Wait for server to start
      run: sleep 10

    - name: Run tests with Playwright
      run: npm run test
