name: Start app and run UI tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14' # Adjust this to a valid Node.js version

    - name: Install dependencies
      run: npm install

    - name: Start frontend and server
      run: |
        npm run start &
        cd server
        node server.js

    - name: Wait for server to start
      run: sleep 10

    - name: Run tests with Playwright
      run: npm run test
